# File: configs/default.yaml
env:
  num_agents: 4
  world_size: 6.0
  r_safety: 0.5
  r_conflict: 1.0
  gamma: 1.0
  dt: 0.1
training:
  steps: 10000
  episode_length: 100
  lr: 0.0005
evaluation:
  steps: 200